# This is a GitLab CI/CD configuration file (.gitlab-ci.yml)
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/

stages:
  - build

build-setup-cli:
  stage: build
  image: golang:alpine3.18
  script:
    - cd node-setup
    - go version
    - go build -v ./...
  only:
    - push

build-java-applications:
  stage: build
  image: eclipse-temurin:17-alpine
  script:
    - './gradlew clean build test'
  only:
    - push