# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

defaults:
  run:
    working-directory: node-setup

name: Go

on:
  push:

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Build
      run: go build -v ./...

    # No tests added
    #- name: Test
    #  run: go test -v ./...
